Repository ynput/ayon-hiero, pull requests merged in 2024-11, with the labels that each got.

#14 Finish Hiero update to new publisher #14
  client/ayon_hiero/api/__init__.py
  client/ayon_hiero/api/constants.py
  client/ayon_hiero/api/lib.py
  client/ayon_hiero/api/menu.py
  client/ayon_hiero/api/otio/hiero_export.py
  client/ayon_hiero/api/otio/utils.py
  client/ayon_hiero/api/pipeline.py
  client/ayon_hiero/api/plugin.py
  client/ayon_hiero/api/startup/Python/Startup/Startup.py
  client/ayon_hiero/api/tags.py
  client/ayon_hiero/plugins/create/create_shot_clip.py
  client/ayon_hiero/plugins/create/create_workfile.py
  client/ayon_hiero/plugins/load/load_effects.py
  client/ayon_hiero/plugins/publish/collect_audio.py
  client/ayon_hiero/plugins/publish/collect_frame_tag_instances.py
  client/ayon_hiero/plugins/publish/collect_otio_timeline.py
  client/ayon_hiero/plugins/publish/collect_plates.py
  client/ayon_hiero/plugins/publish/collect_shots.py
  client/ayon_hiero/plugins/publish/collect_workfile.py
  client/ayon_hiero/plugins/publish/extract_clip_effects.py
  client/ayon_hiero/plugins/publish/extract_workfile.py
  client/ayon_hiero/plugins/publish/precollect_instances.py
  client/ayon_hiero/plugins/publish/precollect_workfile.py
Labels: type: feature, bump minor

#17 Fix timecode detection and image sequence source range on OTIO AYON exporter for Hiero.
  client/ayon_hiero/api/otio/hiero_export.py
Labels: type: enhancement

#27 Removing old API methods
  client/ayon_hiero/api/__init__.py
  client/ayon_hiero/api/lib.py
  client/ayon_hiero/api/pipeline.py
  client/ayon_hiero/plugins/create/create_shot_clip.py
Labels: type: enhancement

#31 Fixing distribution of otioClip attribute to plates
  client/ayon_hiero/plugins/create/create_shot_clip.py
  client/ayon_hiero/plugins/publish/collect_audio.py
  client/ayon_hiero/plugins/publish/collect_plates.py
  client/ayon_hiero/plugins/publish/collect_shots.py
Labels: type: bug, sponsored
