Repository ynput/ayon-hiero, pull requests merged in 2025-09, with the labels that each got.

#85 Fixes clip loader track assignment
  client/ayon_hiero/api/plugin.py
  client/ayon_hiero/plugins/load/load_effects.py
Labels: type: bug

#90 Create: Use kwargs to call product name functions
  client/ayon_hiero/plugins/create/create_workfile.py
Labels: type: enhancement

#88 Re-introduce comments from tags
  client/ayon_hiero/plugins/publish/collect_tag_comments.py
  client/ayon_hiero/plugins/publish_old_workflow/collect_tag_comments.py
Labels: type: enhancement, sponsored

#86 AY-7790 Add parenting of instances
  client/ayon_hiero/plugins/create/create_shot_clip.py
Labels: type: enhancement
