Repository ynput/ayon-hiero, pull requests merged in 2025-02, with the labels that each got.

#44 Add creator attributes to be able to disable effect discovery and publishing for clip from plate instances.
  client/ayon_hiero/plugins/create/create_shot_clip.py
  client/ayon_hiero/plugins/publish/collect_clip_effects.py
Labels: type: enhancement

#47 AY-7460 Fix clip source resolution detection from timeline
  client/ayon_hiero/plugins/publish/collect_shots.py
Labels: type: bug, sponsored

#49 Chore: Remove 'six' usage
  client/ayon_hiero/plugins/load/load_effects.py
Labels: type: enhancement

#45 AY-7235 Restrict shot/plate/audio instance collection from selected clips in the timeline
  client/ayon_hiero/plugins/create/create_shot_clip.py
  server/settings/create_plugins.py
Labels: type: enhancement, sponsored

#50 Improve create_shot_clip code readability.
  client/ayon_hiero/api/plugin.py
  client/ayon_hiero/plugins/create/create_shot_clip.py
  client/ayon_hiero/plugins/publish/collect_audio.py
  client/ayon_hiero/plugins/publish/collect_plates.py
Labels: type: enhancement

#52 Fix 'file' knob export for OCIOFileTransform.
  client/ayon_hiero/plugins/publish/collect_clip_effects.py
Labels: type: bug, sponsored
